/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mobileProgramming: [{ type: 'autogenerated', dirName: 'mobile-programming' }],
  sistemEmbedded: [{ type: 'autogenerated', dirName: 'sistem-embedded' }],
};

module.exports = sidebars;
